/**
 * @file patterns.cpp
 * @brief This file contains a function to generate a specific pattern of stars
 *        based on the input size.
 *
 * The pattern generated by the function `pattern3` is a right-aligned triangle
 * of stars, where the number of rows and columns is determined by the input
 * parameter `n`.
 */
#include <iostream>
using namespace std;

void pattern1(int n)
{
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j <= i; j++)
        {
            cout << "*";
        }
        cout << "\n";
    }
}

void pattern2(int n)
{
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n - i; j++)
        {
            cout << "*";
        }
        cout << "\n";
    }
}

void pattern3(int n)
{
    for (int i = n; i > 0; i--)
    {
        for (int j = 1; j <= n; j++)
        {
            if (j < i)
            {
                cout << " ";
            }
            else
            {
                cout << "*";
            }
        }
        cout << "\n";
    }
}

int main()
{
    pattern1(5);
    pattern2(5);
    pattern3(5);
    return 0;
}